In [9]:
import nltk
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\athar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [10]:
corpus = [
    "I love natural language processing",
    "Natural language processing is fun",
    "I love machine learning"
]

In [11]:
print("Corpus:")
for i, doc in enumerate(corpus, 1):
    print(f"{i}. {doc}")

print("\n" + "-"*60)


Corpus:
1. I love natural language processing
2. Natural language processing is fun
3. I love machine learning

------------------------------------------------------------


In [12]:
count_vectorizer = CountVectorizer()
bow_counts = count_vectorizer.fit_transform(corpus)

In [13]:
print("Bag-of-Words (Count Occurrence):")
print(count_vectorizer.get_feature_names_out())
print(bow_counts.toarray())

print("\n" + "-"*60)

Bag-of-Words (Count Occurrence):
['fun' 'is' 'language' 'learning' 'love' 'machine' 'natural' 'processing']
[[0 0 1 0 1 0 1 1]
 [1 1 1 0 0 0 1 1]
 [0 0 0 1 1 1 0 0]]

------------------------------------------------------------


In [14]:
bow_normalized = bow_counts.toarray().astype(float)


In [15]:
for i in range(len(bow_normalized)):
    bow_normalized[i] /= bow_normalized[i].sum()

In [24]:
print("Bag-of-Words (Normalized Count):")
print(bow_normalized)
print("\n" + "-"*60)

Bag-of-Words (Normalized Count):
[[0.         0.         0.25       0.         0.25       0.
  0.25       0.25      ]
 [0.2        0.2        0.2        0.         0.         0.
  0.2        0.2       ]
 [0.         0.         0.         0.33333333 0.33333333 0.33333333
  0.         0.        ]]

------------------------------------------------------------


In [18]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)

In [25]:
print("TF-IDF:")
print(tfidf_vectorizer.get_feature_names_out())
print(tfidf_matrix.toarray())
print("\n" + "-"*60)

TF-IDF:
['fun' 'is' 'language' 'learning' 'love' 'machine' 'natural' 'processing']
[[0.         0.         0.5        0.         0.5        0.
  0.5        0.5       ]
 [0.51741994 0.51741994 0.3935112  0.         0.         0.
  0.3935112  0.3935112 ]
 [0.         0.         0.         0.62276601 0.4736296  0.62276601
  0.         0.        ]]

------------------------------------------------------------


In [21]:
tokenized_corpus = [nltk.word_tokenize(doc.lower()) for doc in corpus]

word2vec_model = Word2Vec(
    sentences=tokenized_corpus,
    vector_size=50,
    window=3,
    min_count=1,
    workers=1
)

In [22]:
print("Word2Vec Embedding for word 'language':")
print(word2vec_model.wv['language'])

Word2Vec Embedding for word 'language':
[-0.01631583  0.0089916  -0.00827415  0.00164907  0.01699724 -0.00892435
  0.009035   -0.01357392 -0.00709698  0.01879702 -0.00315531  0.00064274
 -0.00828126 -0.01536538 -0.00301602  0.00493959 -0.00177605  0.01106732
 -0.00548595  0.00452013  0.01091159  0.01669191 -0.00290748 -0.01841629
  0.0087411   0.00114357  0.01488382 -0.00162657 -0.00527683 -0.01750602
 -0.00171311  0.00565313  0.01080286  0.01410531 -0.01140624  0.00371764
  0.01217773 -0.0095961  -0.00621452  0.01359526  0.00326295  0.00037983
  0.00694727  0.00043555  0.01923765  0.01012121 -0.01783478 -0.01408312
  0.00180291  0.01278507]
